In [1]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time


mixer.init()
sound = mixer.Sound('3.wav')

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_alt.xml")
eye_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_eye.xml")
model = load_model(os.path.join("models", "model.h5"))

lbl = ['Close', 'Open']

path = os.getcwd()
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score = 0

while (True):
    ret, frame = cap.read()
    height, width = frame.shape[:2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_cascade.detectMultiScale(
        gray, minNeighbors=3, scaleFactor=1.1, minSize=(25, 25))
    eyes = eye_cascade.detectMultiScale(gray, minNeighbors=2, scaleFactor=1.1)

    cv2.rectangle(frame, (0, height-50), (200, height),
                  (0, 0, 0), thickness=cv2.FILLED)

    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 0), 3)

    for (x, y, w, h) in eyes:

        eye = frame[y:y+h, x:x+w]
        # eye = cv2.cvtColor(eye,cv2.COLOR_BGR2GRAY)
        eye = cv2.resize(eye, (80, 80))
        eye = eye/255
        eye = eye.reshape(80, 80, 3)
        eye = np.expand_dims(eye, axis=0)
        prediction = model.predict(eye)
        print(prediction)
       # Condition for Close
        if prediction[0][0] > 0.30:
            cv2.putText(frame, "Closed", (10, height-20), font,
                        1, (255, 255, 255), 1, cv2.LINE_AA)
            cv2.putText(frame, 'Score:'+str(score), (100, height-20),
                        font, 1, (255, 255, 255), 1, cv2.LINE_AA)
            score = score+1
            # print("Close Eyes")
            if (score >= 15):
                try:
                    sound.play()
                except:  # isplaying = False
                    pass
            if (score < 15):
                sound.stop()

        # Condition for Open
        elif prediction[0][1] > 0.90:
            score = score - 1
            if (score < 0):
                score = 0
            cv2.putText(frame, "Open", (10, height-20), font,
                        1, (255, 255, 255), 1, cv2.LINE_AA)
            # print("Open Eyes")
            cv2.putText(frame, 'Score:'+str(score), (100, height-20),
                        font, 1, (255, 255, 255), 1, cv2.LINE_AA)

    cv2.imshow('Driver Drowsiness System', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        sound.stop()
        break
cap.release()
cv2.destroyAllWindows()

pygame 2.1.3 (SDL 2.0.22, Python 3.9.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
1/1 [==============================] - 4s 4s/step
[[2.4011436e-04 9.9975985e-01]]
1/1 [==============================] - 0s 57ms/step
[[0.0160655  0.98393446]]
1/1 [==============================] - 0s 60ms/step
[[0.99692446 0.00307559]]
1/1 [==============================] - 0s 56ms/step
[[0.9314775  0.06852251]]
1/1 [==============================] - 0s 55ms/step
[[0.9719293  0.02807072]]
1/1 [==============================] - 0s 58ms/step
[[3.1768135e-10 1.0000000e+00]]
1/1 [==============================] - 0s 48ms/step
[[9.9979275e-01 2.0724366e-04]]
1/1 [==============================] - 0s 49ms/step
[[0.10018993 0.8998101 ]]
1/1 [==============================] - 0s 51ms/step
[[0.9635168  0.03648327]]
1/1 [==============================] - 0s 55ms/step
[[4.045318e-05 9.999596e-01]]
1/1 [==============================] - 0s 55ms/step
[[0.07713867 0.9228613 ]]
1/1 [====

1/1 [==============================] - 0s 63ms/step
[[0.43973663 0.56026334]]
1/1 [==============================] - 0s 47ms/step
[[0.97713655 0.02286345]]
1/1 [==============================] - 0s 56ms/step
[[0.28127795 0.71872205]]
